#define ELEM_START 1
#define ELEM_NAME_NON_EMPTY 2
#define ELEM_NAME_EMPTY 3
#define ATTR 4
#define ELEM_END 5
#define TEXT 6
#define ELEM_CLOSE 7
#define ELEM_CLOSE_NAME 8
#define XML_DEC_OPEN 9
#define XML_DEC_CLOSE 10
#define XML_DEC_ATTR 11
