#define ELEM_START 0
#define ELEM_NAME_NON_EMPTY 1
#define ELEM_NAME_EMPTY 2
#define ATTR 3
#define ELEM_END 4
#define TEXT 5
#define ELEM_CLOSE 6
#define ELEM_CLOSE_NAME 7
#define XML_DEC_OPEN 8
#define XML_DEC_CLOSE 9
#define XML_DEC_ATTR 10
